name: Automate PR from Dev to QA

on:
  workflow_dispatch: # Manually trigger the workflow
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install @octokit/rest
        run: npm install @octokit/rest

      - name: Create Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require('@octokit/rest');
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            async function createPullRequest() {
              try {
                const { data: branches } = await octokit.repos.listBranches({
                  owner: process.env.GITHUB_REPOSITORY_OWNER,
                  repo: process.env.GITHUB_REPOSITORY,
                });

                const devBranch = branches.find(branch => branch.name === 'dev');
                const qaBranch = branches.find(branch => branch.name === 'qa');

                const pr = await octokit.pulls.create({
                  owner: process.env.GITHUB_REPOSITORY_OWNER,
                  repo: process.env.GITHUB_REPOSITORY,
                  title: 'Automated Pull Request from Dev to QA',
                  head: devBranch.name,
                  base: qaBranch.name,
                  body: 'This is an automated pull request from the dev branch to the qa branch.'
                });

                console.log(`Pull request created: ${pr.data.html_url}`);
              } catch (error) {
                console.error('Error creating pull request:', error);
                process.exit(1);
              }
            }

            createPullRequest();
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
